# Generated by Django 3.1.1 on 2020-10-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_album_album_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
